// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEAY4x_r2GBzjjtm5Dqj1q9vo5gDh89ko',
    appId: '1:355108186758:web:f10d945fedc86488697f07',
    messagingSenderId: '355108186758',
    projectId: 'iotl6-8ffd4',
    authDomain: 'iotl6-8ffd4.firebaseapp.com',
    storageBucket: 'iotl6-8ffd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCstJHhTXLbmSSx5mMuvRpPn-HBfSm6Feg',
    appId: '1:355108186758:android:3053810527e8140c697f07',
    messagingSenderId: '355108186758',
    projectId: 'iotl6-8ffd4',
    storageBucket: 'iotl6-8ffd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv-CdP71ktduAQpb_jErCYqaxcBs5gSHw',
    appId: '1:355108186758:ios:70f2c4e12b9bdd89697f07',
    messagingSenderId: '355108186758',
    projectId: 'iotl6-8ffd4',
    storageBucket: 'iotl6-8ffd4.appspot.com',
    iosClientId: '355108186758-4qvbd5pdus6bnm8vpsefed1u34kncj5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotL6',
  );
}
